#! /usr/bin/bash

DIRang=/path/to/angsd
DIRngs=/path/to/ngsRelate
DIRout=/path/to/output/files

#path to the where bams are
working_path=/path/to/bam

#path to the bamlist
bam_list=/path/to/bamlists
angsd_200K=/path/to/angsd_200K.file
idlist=/path/to/idlists
maf_file=/path/to/maf.frq #maf file



# Executing ANGSD command
$DIRang -b ${bam_list} -gl 2 -domajorminor 1 -domaf 1 -doGlf 2 -sites ${angsd_file} -out $DIRout/angsd_all

# Change directory to the output directory
cd ${DIRout}

# Unzipping the beagle.gz file and perform GLF subsetting for each sample with an Rscript
gunzip $DIRout/angsd_all.beagle.gz
Rscript ${DIRout}/GLF_subset.R 

# Preparing mafs
gunzip $DIRout/maf_file
awk '{print $1"_"$2, $0}' $DIRout/maf_file > $DIRout/maf_file_with_chr_pos


# Preparing pair names
Rscript ${DIRout}/pairnames_script.R
sed 1d ${DIRout}/pair_names > ${DIRout}/pairnames_file
rm ${DIRout}/pair_names

echo DONE
