#!/bin/bash -l
#SBATCH -p partition-name
#SBATCH -n 1
#SBATCH -t time
#SBATCH -J job-name
#SBATCH -o slurm-%j-%N-%u.out
#SBATCH -e slurm-%J-%N-%u.err


i=$1

DIRout=/path/to/pairwise/beagle/files  # output path
DIRngs=/path/to/ngsrelate
pair_name=/path/to/pair/names
DIRresult=/path/to/ngsrelate/results

mafs_file=path/to/mafs/file

cd ${DIRout}


for pair in $(cat ${pair_name})
do 

pairbase=$(basename $pair)

cat $DIRout/data_${pairbase}.beagle | cut -f1 | sed 1,2d   > $DIRout/${pairbase}_${i}_snp.list


SAMPLE_SIZES=(1000 5000 10000 20000 50000)
REPLICATES=5
y=1000

# Loop through the sample sizes
for SIZE in "${SAMPLE_SIZES[@]}"; do
    SIZE_LABEL=$(($SIZE/$y))


    # Preparing downsampled SNP list
    cat $DIRout/${pairbase}_${i}_snp.list | shuf -n ${SIZE} | sort -V  > $DIRout/snps_${pairbase}_${i}_${SIZE_LABEL}

    # Preparing frequency file for ngsRelate accordingly
    grep -w -f $DIRout/snps_${pairbase}_${i}_${SIZE_LABEL} $DIRout/mafs_file | cat | cut -f5  > $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file

    # Adding noise to freqs using Rscript
    Rscript noise_script.R "$DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file" $SIZE

    # Preparing GLFs for ngsRelate accordingly
    grep -w -f $DIRout/snps_${pairbase}_${i}_${SIZE_LABEL} $DIRout/data_${pairbase}.beagle > $DIRout/${pairbase}_${i}_${SIZE_LABEL}.beagle
    gzip $DIRout/${pairbase}_${i}_${SIZE_LABEL}.beagle 

    # Converting GLFs into binary GLFs
    zcat $DIRout/${pairbase}_${i}_${SIZE_LABEL}.beagle.gz | perl -an -e 'for($i=3; $i<=$#F; $i++){print(pack("d",($F[$i]==0 ? -inf : log($F[$i]))))}' > $DIRout/${pairbase}_${i}_${SIZE_LABEL}.glf.gz

    # Executing ngsRelate
    $DIRngs -g $DIRout/${pairbase}_${i}_${SIZE_LABEL}.glf.gz -n 2 -f $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file -l 0 -O $DIRresult/${pairbase}_${i}_${SIZE_LABEL}
    $DIRngs -g $DIRout/${pairbase}_${i}_${SIZE_LABEL}.glf.gz -n 2 -f $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file_noise05 -l 0 -O $DIRresult/${pairbase}_${i}_${SIZE_LABEL}_noise05
    $DIRngs -g $DIRout/${pairbase}_${i}_${SIZE_LABEL}.glf.gz -n 2 -f $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file_noise1 -l 0 -O $DIRresult/${pairbase}_${i}_${SIZE_LABEL}_noise1


# Removing unnecessary files
rm $DIRout/snps_${pairbase}_${i}_${SIZE_LABEL}
rm $DIRout/${pairbase}_${i}_${SIZE_LABEL}.beagle.gz
rm $DIRout/${pairbase}_${i}_${SIZE_LABEL}.glf.gz
rm $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file 
rm $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file_noise05
rm $DIRout/freq_${pairbase}_${i}_${SIZE_LABEL}.file_noise1

done
rm $DIRout/${pairbase}_${i}_snp.list

done

